# Generated by Django 6.0.5 on 2026-05-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(default='第4章 陣列', max_length=100)),
                ('content', models.TextField(verbose_name='題目敘述')),
                ('option_A', models.CharField(max_length=255, verbose_name='選項 A')),
                ('option_B', models.CharField(max_length=255, verbose_name='選項 B')),
                ('option_C', models.CharField(max_length=255, verbose_name='選項 C')),
                ('option_D', models.CharField(max_length=255, verbose_name='選項 D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='正確答案')),
            ],
        ),
    ]
