# Generated by Django 6.0.5 on 2026-05-28 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('易', '易'), ('中', '中'), ('難', '難')], default='中', max_length=10, verbose_name='難易度'),
        ),
        migrations.CreateModel(
            name='QuizRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='測驗得分')),
                ('total_questions', models.IntegerField(verbose_name='總題數')),
                ('date_taken', models.DateTimeField(auto_now_add=True, verbose_name='測驗時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='學生')),
            ],
        ),
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_count', models.IntegerField(default=1, verbose_name='答錯次數')),
                ('last_wrong_time', models.DateTimeField(auto_now=True, verbose_name='最後答錯時間')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
