# Generated by Django 6.0.5 on 2026-06-01 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_difficulty_quizrecord_wrongquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option_A',
            new_name='option_a',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_B',
            new_name='option_b',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_C',
            new_name='option_c',
        ),
        migrations.AlterUniqueTogether(
            name='wrongquestion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_D',
        ),
        migrations.AddField(
            model_name='wrongquestion',
            name='user_answer',
            field=models.CharField(default='A', max_length=1, verbose_name='學生選的錯誤答案'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(verbose_name='題目內容'),
        ),
        migrations.AlterField(
            model_name='wrongquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='錯題'),
        ),
        migrations.AlterField(
            model_name='wrongquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='學生'),
        ),
        migrations.DeleteModel(
            name='QuizRecord',
        ),
        migrations.RemoveField(
            model_name='wrongquestion',
            name='error_count',
        ),
        migrations.RemoveField(
            model_name='wrongquestion',
            name='last_wrong_time',
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='選項 D'),
        ),
    ]
